app/contextMenu.ts
app/download.ts
app/plugins/patreon.ts
app/ui/siteActions.ts
app/utils/file.ts
manifest/manifest.json

- Fixed download path variable sanitization
- Improved fallback logic for normal getMedia calls when attributes aren't specified

- Fixed context save not populating the extension

---

app/plugins/ekas.ts

Closes https://github.com/Simon-Tesla/RaccoonyWebEx/issues/41 (in case the title link doesn't work.)

Eka's plugin: handle the new thumbnail box on some submission pages.  Closes #41.

---

app/contextMenu.ts
app/options.tsx
app/plugins/weasyl.ts
app/ui/siteSettingsUi.tsx
gulpfile.js
package-lock.json
package.json

Updates Typescript to v 3.7.5, React to 16.12, web-ext to 4.1, as well as various other updates

Update various packages

---

app/definitions.ts
app/plugins/deviantart.ts
app/ui/siteActions.ts

Fixes the dA plugin for both the classic site and the new Eclipse theme. Fixes #39, #36

deviantArt Eclipse bugfixes

---

gulpfile.js
package-lock.json
package.json

Various package minver updates

Update gulp to v. 4.0.2 (needed to upgrade to node 12.16 LTS)

---

CHANGELOG.md
manifest/manifest.json
package.json

Finally packaging the release! More than a year after 1.2.2! :P

Update manifest to 1.2.3

---

gulpfile.js

Fix build to define sign:firefox before it's used

---

app/openTabs.ts
app/settings.ts
app/typedefs.d.ts
app/ui/siteSettingsUi.tsx
package-lock.json
package.json

This changes the behavior of open in tabs to open each set of tabs serially instead of all at once, and also sets the default to open tabs one at a time instead of the old placeholder tab behavior.
Resolves #28

Add a queue to Open in Tabs (#28)

---

app/plugins/e621.ts

Fix for #104 originally written by @Eupeptic1

Fix author/artist name bug on e621 (#104)

---

package-lock.json
package.json

* Update web-ext to 6.3.0
* Ran npm audit fix

Update package dependency versions

---

app/definitions.ts
app/download.ts
app/plugins/base.ts
app/plugins/index.ts
app/plugins/newgrounds.ts
app/ui/page/page.tsx
app/ui/siteActions.ts
app/utils/dom.ts
manifest/manifest.json

- Refactored the download checking code to be separate from getMedia
- Made Newgrounds Video download work correctly; waits for user to start playing before download.
- Fixes #125

Added Newgrounds support (#125)

---

app/ui/page/page.tsx

Fix Furaffinity zindex bug with fullscreen overlay (#150)

---

app/plugins/patreon.ts

- Updated the mutation selector so Raccoony runs properly
- Updated the scraping for author and description
- Added support for better right-click downloading that preserves more metadata
- Added audio post support

Fix patreon scraper

---

app/plugins/index.ts
app/plugins/itaku.ts
app/ui/page/page.tsx
app/utils/dom.ts
manifest/manifest.json

Add Itaku support

---

app/definitions.ts
app/plugins/index.ts
app/plugins/subscribestar.ts
app/ui/siteActions.ts
manifest/manifest.json

Add SubscribeStar support

---

app/plugins/itaku.ts

Fix Itaku plugin, add video and blacklist support

---

app/plugins/base.ts
app/plugins/patreon.ts
app/ui/page/page.tsx

Fix Patreon plugin, MutationObserver logic

---

app/plugins/patreon.ts

Fix Patreon JSON metadata parsing bug

---

app/plugins/e621.ts

Fix link detection in e621 plugin (2024-11 DOM update) 

---

app/definitions.ts
app/plugins/furaffinity.ts
app/ui/page/page.tsx
app/utils/dom.ts

[FurAffinity] Add hasContentWarning support and skip autofullscreen

---

app/plugins/e621.ts

E621: fix video URL scraping (fixes #208)
